---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Execute command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: echo this is a test > yes.txt
