name: Flat
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch: null
  schedule:
    - cron: "*/30 * * * *"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/docker/docker-install/master/install.sh
          downloaded_filename: docker_install.sh
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
          downloaded_filename: nvm-sh_install.sh
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://cloudron.io/cloudron-setup
          downloaded_filename: cloudron-setup.sh
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://repo.jellyfin.org/install-debuntu.sh
          downloaded_filename: jellyfin_install-debuntu.sh
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/meilisearch/meilisearch/latest/download-latest.sh
          downloaded_filename: meilisearch_latest.sh
